const iconCategories = [
    { id: 'all', name: 'Все', icon: 'apps' },
    // Расширенные категории файловой системы
    { id: 'file', name: 'Файлы', icon: 'description' },
    { id: 'folders', name: 'Папки', icon: 'folder' },
    { id: 'storage', name: 'Хранилища и Диски', icon: 'hard_drive' },
    { id: 'cloud', name: 'Облако', icon: 'cloud' },
    { id: 'file_actions', name: 'Действия', icon: 'drive_file_move' },
    { id: 'search_view', name: 'Поиск и вид', icon: 'search' },
    { id: 'access', name: 'Доступ и защита', icon: 'lock' },
    { id: 'devices', name: 'Устройства и сеть', icon: 'devices' },
    { id: 'library', name: 'Библиотека', icon: 'library_books' },
    // Исходные категории
    { id: 'media', name: 'Медиа', icon: 'image' },
    { id: 'dev', name: 'Код', icon: 'code' },
    { id: 'tools', name: 'Инструменты', icon: 'settings' },
    { id: 'comm', name: 'Связь', icon: 'chat' },
    { id: 'mapping', name: 'Топография и Карты', icon: 'map' }
];

const materialCatalog = [
    // === КАТЕГОРИЯ: ПАПКИ (folders) ===
    { name: 'folder', label: 'Папка', category: 'folders' },
    { name: 'folder_open', label: 'Папка (открыта)', category: 'folders' },
    { name: 'create_new_folder', label: 'Новая папка', category: 'folders' },
    { name: 'folder_shared', label: 'Общая папка', category: 'folders' },
    { name: 'folder_special', label: 'Избранная папка', category: 'folders' },
    { name: 'folder_zip', label: 'Архив (ZIP)', category: 'folders' },
    { name: 'folder_copy', label: 'Копия папки', category: 'folders' },
    { name: 'folder_delete', label: 'Удалить папку', category: 'folders' },
    { name: 'folder_off', label: 'Скрытая папка', category: 'folders' },
    { name: 'drive_folder_upload', label: 'Загрузка папки', category: 'folders' },
    { name: 'snippet_folder', label: 'Папка с фрагментами', category: 'folders' },
    { name: 'rule_folder', label: 'Папка с правилами', category: 'folders' },
    { name: 'folder_managed', label: 'Управляемая папка', category: 'folders' },
    { name: 'folder_supervised', label: 'Контролируемая папка', category: 'folders' },
    { name: 'workspaces', label: 'Рабочее пространство', category: 'folders' },
    { name: 'topic', label: 'Тема (набор файлов)', category: 'folders' },
    { name: 'perm_media', label: 'Папка медиа', category: 'folders' },
    
    // === КАТЕГОРИЯ: ФАЙЛЫ И ТИПЫ (file) ===
    { name: 'description', label: 'Документ', category: 'file' },
    { name: 'insert_drive_file', label: 'Файл', category: 'file' },
    { name: 'draft', label: 'Черновик', category: 'file' },
    { name: 'file_present', label: 'Вложение', category: 'file' },
    { name: 'article', label: 'Статья', category: 'file' },
    { name: 'text_snippet', label: 'Текстовый фрагмент', category: 'file' },
    { name: 'picture_as_pdf', label: 'PDF', category: 'file' },
    { name: 'csv', label: 'CSV', category: 'file' },
    { name: 'file_json', label: 'JSON', category: 'file' },
    { name: 'html', label: 'HTML', category: 'file' },
    { name: 'css', label: 'CSS', category: 'file' },
    { name: 'javascript', label: 'JavaScript', category: 'file' },
    { name: 'php', label: 'PHP', category: 'file' },
    { name: 'audio_file', label: 'Аудиофайл', category: 'file' },
    { name: 'video_file', label: 'Видеофайл', category: 'file' },
    { name: 'table_chart', label: 'Таблица', category: 'file' },
    { name: 'grid_on', label: 'Сетка', category: 'file' },
    { name: 'clarify', label: 'Список', category: 'file' },
    { name: 'note', label: 'Заметка', category: 'file' },
    { name: 'sticky_note_2', label: 'Стикер', category: 'file' },
    { name: 'receipt_long', label: 'Квитанция', category: 'file' },
    { name: 'find_in_page', label: 'Поиск в файле', category: 'file' },
    { name: 'assignment', label: 'Задание/Документ', category: 'file' },
    { name: 'assignment_ind', label: 'Личное дело', category: 'file' },
    { name: 'assignment_late', label: 'Просроченный документ', category: 'file' },
    { name: 'assignment_turned_in', label: 'Документ выполнен', category: 'file' },
    { name: 'contract', label: 'Договор', category: 'file' },
    { name: 'contract_edit', label: 'Редактировать договор', category: 'file' },
    { name: 'contract_delete', label: 'Удалить договор', category: 'file' },
    { name: 'code_blocks', label: 'Блоки кода', category: 'file' },
    { name: 'checklist', label: 'Чек-лист', category: 'file' },
    { name: 'checklist_rtl', label: 'Чек-лист (RTL)', category: 'file' },
    { name: 'bookmark', label: 'Закладка', category: 'file' },
    { name: 'bookmarks', label: 'Закладки', category: 'file' },
    { name: 'bookmark_add', label: 'Добавить закладку', category: 'file' },
    { name: 'bookmark_manager', label: 'Менеджер закладок', category: 'file' },
    { name: 'edit_document', label: 'Редактировать документ', category: 'file' },
    { name: 'difference', label: 'Сравнение файлов', category: 'file' },
    { name: 'text_fields', label: 'Текстовые поля', category: 'file' },
    { name: 'subject', label: 'Содержание', category: 'file' },
    { name: 'summarize', label: 'Сводка', category: 'file' },
    { name: 'checkbook', label: 'Чековая книжка', category: 'file' },

    // === КАТЕГОРИЯ: ДЕЙСТВИЯ С ФАЙЛАМИ (file_actions) ===
    { name: 'file_download', label: 'Скачать файл', category: 'file_actions' },
    { name: 'file_upload', label: 'Загрузить файл', category: 'file_actions' },
    { name: 'file_copy', label: 'Копировать файл', category: 'file_actions' },
    { name: 'file_open', label: 'Открыть файл', category: 'file_actions' },
    { name: 'drive_file_move', label: 'Переместить', category: 'file_actions' },
    { name: 'drive_file_rename_outline', label: 'Переименовать', category: 'file_actions' },
    { name: 'save', label: 'Сохранить', category: 'file_actions' },
    { name: 'save_as', label: 'Сохранить как', category: 'file_actions' },
    { name: 'attachment', label: 'Прикрепить', category: 'file_actions' },
    { name: 'attach_file', label: 'Скрепка', category: 'file_actions' },
    { name: 'delete', label: 'Удалить', category: 'file_actions' },
    { name: 'delete_forever', label: 'Удалить навсегда', category: 'file_actions' },
    { name: 'restore', label: 'Восстановить', category: 'file_actions' },
    { name: 'restore_page', label: 'Восстановить из корзины', category: 'file_actions' },
    { name: 'content_copy', label: 'Копировать (буфер)', category: 'file_actions' },
    { name: 'content_cut', label: 'Вырезать', category: 'file_actions' },
    { name: 'content_paste', label: 'Вставить', category: 'file_actions' },
    { name: 'print', label: 'Печать', category: 'file_actions' },
    { name: 'document_scanner', label: 'Скан', category: 'file_actions' },
    { name: 'create', label: 'Создать / Изменить', category: 'file_actions' },
    { name: 'compress', label: 'Сжать в архив', category: 'file_actions' },
    { name: 'compare_arrows', label: 'Сравнить', category: 'file_actions' },
    { name: 'content_paste_go', label: 'Вставить и перейти', category: 'file_actions' },
    { name: 'content_paste_off', label: 'Вставка недоступна', category: 'file_actions' },
    { name: 'content_paste_search', label: 'Поиск в буфере', category: 'file_actions' },
    { name: 'copy_all', label: 'Копировать всё', category: 'file_actions' },
    { name: 'backup_table', label: 'Резервная таблица', category: 'file_actions' },
    { name: 'move_up', label: 'Переместить вверх', category: 'file_actions' },
    { name: 'move_down', label: 'Переместить вниз', category: 'file_actions' },
    { name: 'swap_horiz', label: 'Обмен местами', category: 'file_actions' },

    // === КАТЕГОРИЯ: ОБЛАКО И СИНХРОНИЗАЦИЯ (cloud) ===
    { name: 'cloud', label: 'Облако', category: 'cloud' },
    { name: 'cloud_upload', label: 'Загрузка в облако', category: 'cloud' },
    { name: 'cloud_download', label: 'Скачать из облака', category: 'cloud' },
    { name: 'cloud_sync', label: 'Синхронизация', category: 'cloud' },
    { name: 'cloud_done', label: 'Синхронизировано', category: 'cloud' },
    { name: 'cloud_off', label: 'Без сети', category: 'cloud' },
    { name: 'cloud_queue', label: 'Очередь облака', category: 'cloud' },
    { name: 'backup', label: 'Резервная копия', category: 'cloud' },
    { name: 'sync', label: 'Обновление данных', category: 'cloud' },
    { name: 'cloud_alert', label: 'Ошибка облака', category: 'cloud' },
    { name: 'cloud_lock', label: 'Защищённое облако', category: 'cloud' },
    { name: 'cloud_circle', label: 'Облачный аккаунт', category: 'cloud' },
    { name: 'add_to_drive', label: 'Добавить на диск', category: 'cloud' },
    { name: 'drive_file_move_outline', label: 'Переместить на диск', category: 'cloud' },

    // === КАТЕГОРИЯ: ХРАНИЛИЩЕ И НОСИТЕЛИ (storage) ===
    { name: 'storage', label: 'Хранилище', category: 'storage' },
    { name: 'hard_drive', label: 'Жесткий диск', category: 'storage' },
    { name: 'sd_card', label: 'SD-карта', category: 'storage' },
    { name: 'usb', label: 'USB-накопитель', category: 'storage' },
    { name: 'memory', label: 'ОЗУ / Память', category: 'storage' },
    { name: 'archive', label: 'Архив', category: 'storage' },
    { name: 'inventory_2', label: 'Пакет / Ящик', category: 'storage' },
    { name: 'android', label: 'Android', category: 'storage' }, // Из оригинального списка
    { name: 'inventory', label: 'Инвентарь', category: 'storage' },
    { name: 'box', label: 'Коробка', category: 'storage' },
    { name: 'box_add', label: 'Добавить в коробку', category: 'storage' },
    { name: 'box_edit', label: 'Редактировать коробку', category: 'storage' },
    { name: 'unarchive', label: 'Разархивировать', category: 'storage' },
    { name: 'developer_board', label: 'Плата устройства', category: 'storage' },

    // === ОСТАЛЬНЫЕ КАТЕГОРИИ ===
    { name: 'image', label: 'Картинка', category: 'media' },
    { name: 'photo_camera', label: 'Камера', category: 'media' },
    { name: 'photo_library', label: 'Галерея', category: 'media' },
    { name: 'movie', label: 'Видео', category: 'media' },
    { name: 'movie_filter', label: 'Видеофильтр', category: 'media' },
    { name: 'videocam', label: 'Видеокамера', category: 'media' },
    { name: 'music_note', label: 'Музыка', category: 'media' },
    { name: 'headphones', label: 'Наушники', category: 'media' },
    { name: 'mic', label: 'Микрофон', category: 'media' },
    { name: 'graphic_eq', label: 'Эквалайзер', category: 'media' },
    { name: 'palette', label: 'Палитра', category: 'media' },
    { name: 'brush', label: 'Кисть', category: 'media' },
    { name: 'gif_box', label: 'GIF', category: 'media' },
    { name: 'collections', label: 'Коллекция', category: 'media' },
    { name: 'wallpaper', label: 'Обои', category: 'media' },
    { name: 'theaters', label: 'Кино', category: 'media' },
    { name: 'crop', label: 'Обрезка', category: 'media' },
    { name: 'crop_free', label: 'Свободная обрезка', category: 'media' },
    { name: 'crop_original', label: 'Исходный размер', category: 'media' },
    { name: 'crop_square', label: 'Обрезка (квадрат)', category: 'media' },
    { name: 'crop_rotate', label: 'Поворот и обрезка', category: 'media' },
    { name: 'colorize', label: 'Пипетка', category: 'media' },
    { name: 'blur_on', label: 'Размытие вкл', category: 'media' },
    { name: 'blur_off', label: 'Размытие выкл', category: 'media' },
    { name: 'animation', label: 'Анимация', category: 'media' },
    { name: 'album', label: 'Альбом', category: 'media' },
    { name: 'audiotrack', label: 'Аудиодорожка', category: 'media' },
    { name: 'closed_caption', label: 'Субтитры', category: 'media' },
    { name: 'broken_image', label: 'Повреждённое изображение', category: 'media' },
    { name: 'camera_roll', label: 'Плёнка камеры', category: 'media' },
    { name: 'burst_mode', label: 'Серийная съёмка', category: 'media' },

    { name: 'code', label: 'Код', category: 'dev' },
    { name: 'terminal', label: 'Терминал', category: 'dev' },
    { name: 'data_object', label: 'Объект данных', category: 'dev' },
    { name: 'data_array', label: 'Массив данных', category: 'dev' },
    { name: 'integration_instructions', label: 'API-инструкция', category: 'dev' },
    { name: 'bug_report', label: 'Баг-репорт', category: 'dev' },
    { name: 'developer_mode', label: 'Режим разработчика', category: 'dev' },
    { name: 'api', label: 'API', category: 'dev' },
    { name: 'webhook', label: 'Вебхук', category: 'dev' },
    { name: 'dns', label: 'DNS', category: 'dev' },
    { name: 'http', label: 'HTTP', category: 'dev' },
    { name: 'schema', label: 'Схема', category: 'dev' },
    { name: 'account_tree', label: 'Дерево', category: 'dev' },
    { name: 'hub', label: 'Хаб', category: 'dev' },
    { name: 'device_hub', label: 'Узел устройств', category: 'dev' },
    { name: 'code_off', label: 'Код отключён', category: 'dev' },
    { name: 'cell_tower', label: 'Вышка связи', category: 'dev' },
    { name: 'commit', label: 'Коммит (Git)', category: 'dev' },
    { name: 'category', label: 'Категория данных', category: 'dev' },
    { name: 'auto_awesome', label: 'Автоматизация (AI)', category: 'dev' },

    { name: 'settings', label: 'Настройки', category: 'tools' },
    { name: 'build', label: 'Ключ', category: 'tools' },
    { name: 'construction', label: 'Инструменты', category: 'tools' },
    { name: 'tune', label: 'Тонкая настройка', category: 'tools' },
    { name: 'handyman', label: 'Мастер', category: 'tools' },
    { name: 'plumbing', label: 'Сантехника', category: 'tools' },
    { name: 'engineering', label: 'Инженерия', category: 'tools' },
    { name: 'science', label: 'Наука', category: 'tools' },
    { name: 'precision_manufacturing', label: 'Производство', category: 'tools' },
    { name: 'extension', label: 'Расширение', category: 'tools' },
    { name: 'widgets', label: 'Виджеты', category: 'tools' },
    { name: 'dashboard', label: 'Панель управления', category: 'tools' },
    { name: 'speed', label: 'Скорость', category: 'tools' },
    { name: 'admin_panel_settings', label: 'Админ-панель', category: 'tools' },
    { name: 'stylus_note', label: 'Рисунок', category: 'tools' },
    { name: 'contrast', label: 'Контраст', category: 'tools' },
    { name: 'build_circle', label: 'Настройка (круг)', category: 'tools' },
    { name: 'cleaning_services', label: 'Очистка', category: 'tools' },
    { name: 'auto_fix_high', label: 'Автонастройка', category: 'tools' },
    { name: 'auto_delete', label: 'Автоудаление', category: 'tools' },

    { name: 'mail', label: 'Почта', category: 'comm' },
    { name: 'chat', label: 'Чат', category: 'comm' },
    { name: 'forum', label: 'Форум', category: 'comm' },
    { name: 'chat_bubble', label: 'Диалог', category: 'comm' },
    { name: 'sms', label: 'SMS', category: 'comm' },
    { name: 'call', label: 'Звонок', category: 'comm' },
    { name: 'contact_mail', label: 'Контакт по почте', category: 'comm' },
    { name: 'contacts', label: 'Контакты', category: 'comm' },
    { name: 'group', label: 'Группа', category: 'comm' },
    { name: 'groups', label: 'Группы', category: 'comm' },
    { name: 'person', label: 'Пользователь', category: 'comm' },
    { name: 'badge', label: 'Бейдж', category: 'comm' },
    { name: 'share', label: 'Поделиться', category: 'comm' },
    { name: 'send', label: 'Отправить', category: 'comm' },
    { name: 'notifications', label: 'Уведомления', category: 'comm' },
    { name: 'campaign', label: 'Рассылка', category: 'comm' },
    { name: 'contact_page', label: 'Страница контакта', category: 'comm' },
    { name: 'contact_phone', label: 'Контакт (телефон)', category: 'comm' },
    { name: 'contact_emergency', label: 'Экстренный контакт', category: 'comm' },
    { name: 'comment', label: 'Комментарий', category: 'comm' },
    { name: 'comment_bank', label: 'Банк комментариев', category: 'comm' },
    { name: 'call_end', label: 'Завершить звонок', category: 'comm' },
    { name: 'call_missed', label: 'Пропущенный звонок', category: 'comm' },

    // === КАТЕГОРИЯ: ТОПОГРАФИЯ И КАРТЫ (mapping) ===
    { name: 'map', label: 'Карта', category: 'mapping' },
    { name: 'terrain', label: 'Рельеф / Местность', category: 'mapping' },
    { name: 'explore', label: 'Исследование / Компас', category: 'mapping' },
    { name: 'polyline', label: 'Вектор / Маршрут', category: 'mapping' },
    { name: 'layers', label: 'Слои карты', category: 'mapping' },
    { name: 'location_on', label: 'Координата', category: 'mapping' },
    { name: 'my_location', label: 'Мое местоположение', category: 'mapping' },
    { name: 'compass_calibration', label: 'Калибровка', category: 'mapping' },
    { name: 'radar', label: 'Радар / Сканирование', category: 'mapping' },


    // === КАТЕГОРИЯ: ПОИСК И ВИД (search_view) ===
    { name: 'search', label: 'Поиск', category: 'search_view' },
    { name: 'manage_search', label: 'Управление поиском', category: 'search_view' },
    { name: 'saved_search', label: 'Сохранённый поиск', category: 'search_view' },
    { name: 'search_off', label: 'Поиск недоступен', category: 'search_view' },
    { name: 'filter_list', label: 'Фильтр (список)', category: 'search_view' },
    { name: 'filter_alt', label: 'Фильтр', category: 'search_view' },
    { name: 'sort', label: 'Сортировка', category: 'search_view' },
    { name: 'sort_by_alpha', label: 'Сортировка по алфавиту', category: 'search_view' },
    { name: 'grid_view', label: 'Вид сеткой', category: 'search_view' },
    { name: 'view_list', label: 'Вид списком', category: 'search_view' },
    { name: 'view_module', label: 'Вид модулями', category: 'search_view' },
    { name: 'view_agenda', label: 'Вид повесткой', category: 'search_view' },
    { name: 'view_column', label: 'Вид колонками', category: 'search_view' },
    { name: 'table_rows', label: 'Строки таблицы', category: 'search_view' },
    { name: 'format_list_bulleted', label: 'Маркированный список', category: 'search_view' },
    { name: 'calendar_view_month', label: 'Вид: месяц', category: 'search_view' },
    { name: 'calendar_view_week', label: 'Вид: неделя', category: 'search_view' },
    { name: 'calendar_view_day', label: 'Вид: день', category: 'search_view' },
    { name: 'calendar_today', label: 'Календарь', category: 'search_view' },
    { name: 'calendar_month', label: 'Месяц', category: 'search_view' },

    // === КАТЕГОРИЯ: ДОСТУП И ЗАЩИТА (access) ===
    { name: 'lock', label: 'Замок', category: 'access' },
    { name: 'security', label: 'Безопасность', category: 'access' },
    { name: 'lock_open', label: 'Открытый замок', category: 'access' },
    { name: 'key', label: 'Ключ', category: 'access' },
    { name: 'vpn_key', label: 'Ключ доступа', category: 'access' },
    { name: 'shield', label: 'Щит', category: 'access' },
    { name: 'verified_user', label: 'Проверенный пользователь', category: 'access' },
    { name: 'policy', label: 'Политика', category: 'access' },
    { name: 'gpp_good', label: 'Защита в порядке', category: 'access' },
    { name: 'gpp_bad', label: 'Угроза защиты', category: 'access' },
    { name: 'gpp_maybe', label: 'Предупреждение защиты', category: 'access' },
    { name: 'encrypted', label: 'Зашифровано', category: 'access' },
    { name: 'no_encryption', label: 'Без шифрования', category: 'access' },
    { name: 'fingerprint', label: 'Отпечаток пальца', category: 'access' },
    { name: 'password', label: 'Пароль', category: 'access' },
    { name: 'pin', label: 'PIN-код', category: 'access' },
    { name: 'visibility', label: 'Показать', category: 'access' },
    { name: 'visibility_off', label: 'Скрыть', category: 'access' },
    { name: 'crisis_alert', label: 'Критическое предупреждение', category: 'access' },

    // === КАТЕГОРИЯ: УСТРОЙСТВА И СЕТЬ (devices) ===
    { name: 'devices', label: 'Устройства', category: 'devices' },
    { name: 'computer', label: 'Компьютер', category: 'devices' },
    { name: 'laptop', label: 'Ноутбук', category: 'devices' },
    { name: 'desktop_windows', label: 'Настольный ПК', category: 'devices' },
    { name: 'phone_android', label: 'Телефон Android', category: 'devices' },
    { name: 'tablet', label: 'Планшет', category: 'devices' },
    { name: 'tv', label: 'Телевизор', category: 'devices' },
    { name: 'router', label: 'Роутер', category: 'devices' },
    { name: 'wifi', label: 'Wi-Fi', category: 'devices' },
    { name: 'wifi_off', label: 'Wi-Fi выключен', category: 'devices' },
    { name: 'lan', label: 'Локальная сеть', category: 'devices' },
    { name: 'settings_ethernet', label: 'Ethernet', category: 'devices' },
    { name: 'bluetooth', label: 'Bluetooth', category: 'devices' },
    { name: 'usb_off', label: 'USB отключён', category: 'devices' },
    { name: 'scanner', label: 'Сканер', category: 'devices' },

    // === КАТЕГОРИЯ: БИБЛИОТЕКА (library) ===
    { name: 'library_books', label: 'Библиотека документов', category: 'library' },
    { name: 'auto_stories', label: 'Раскрытая книга', category: 'library' },
    { name: 'collections_bookmark', label: 'Коллекция с закладкой', category: 'library' },
    { name: 'menu_book', label: 'Книга (меню)', category: 'library' },
    { name: 'book', label: 'Книга', category: 'library' },
    { name: 'import_contacts', label: 'Импорт из книги', category: 'library' },
    { name: 'video_library', label: 'Видеотека', category: 'library' },
    { name: 'style', label: 'Стиль/Теги', category: 'library' },
    { name: 'label', label: 'Ярлык', category: 'library' },
    { name: 'local_offer', label: 'Метка', category: 'library' }
];
